//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOnCENCOSUD.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOnCENCOSUD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string BF_ObtenerGuia {
            get {
                return ResourceManager.GetString("BF_ObtenerGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string BF_ObtenerTransportista {
            get {
                return ResourceManager.GetString("BF_ObtenerTransportista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM &quot;@EXX_SETUP&quot; where &quot;U_EXX_ADDN&quot; =.
        /// </summary>
        internal static string DeleteSetup {
            get {
                return ResourceManager.GetString("DeleteSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT IFNULL(MAX(CAST(&quot;Code&quot; AS numeric)), 999) + 1 AS Numero FROM &quot;@EXX_SETUP&quot;.
        /// </summary>
        internal static string HanaCorrInstall {
            get {
                return ResourceManager.GetString("HanaCorrInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO &quot;@EXX_SETUP&quot; VALUES.
        /// </summary>
        internal static string HanaInsertSetup {
            get {
                return ResourceManager.GetString("HanaInsertSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select top 1 &quot;AName&quot;,&quot;AddOnVer&quot; from &quot;SBOCOMMON&quot;.&quot;SARI&quot; where &quot;AName&quot; = &apos;AddOnUpdPrice&apos; order by &quot;AddOnVer&quot; desc.
        /// </summary>
        internal static string HanaSari {
            get {
                return ResourceManager.GetString("HanaSari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT ISNULL(MAX(CAST(&quot;Code&quot; AS numeric)), 999) + 1 AS Numero FROM &quot;@EXX_SETUP&quot;.
        /// </summary>
        internal static string SQLCorrInstall {
            get {
                return ResourceManager.GetString("SQLCorrInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select top 1 &quot;AName&quot;,&quot;AddOnVer&quot; from &quot;SBO-COMMON&quot;.&quot;dbo&quot;.&quot;SARI&quot; where &quot;AName&quot; = &apos;AddOnUpdPrice&apos; order by &quot;AddOnVer&quot; desc.
        /// </summary>
        internal static string SQLSari {
            get {
                return ResourceManager.GetString("SQLSari", resourceCulture);
            }
        }
    }
}
